# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_consult_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultWindow(object):
    def setupUi(self, ConsultWindow):
        ConsultWindow.setObjectName("ConsultWindow")
        ConsultWindow.resize(642, 503)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        ConsultWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ConsultWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidgetFacts = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetFacts.setObjectName("listWidgetFacts")
        self.verticalLayout.addWidget(self.listWidgetFacts)
        self.butonUnselcetAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonUnselcetAll.sizePolicy().hasHeightForWidth())
        self.butonUnselcetAll.setSizePolicy(sizePolicy)
        self.butonUnselcetAll.setObjectName("butonUnselcetAll")
        self.verticalLayout.addWidget(self.butonUnselcetAll)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainText.setReadOnly(True)
        self.plainText.setObjectName("plainText")
        self.horizontalLayout.addWidget(self.plainText)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonProcess = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProcess.sizePolicy().hasHeightForWidth())
        self.buttonProcess.setSizePolicy(sizePolicy)
        self.buttonProcess.setObjectName("buttonProcess")
        self.verticalLayout_2.addWidget(self.buttonProcess)
        self.verticalLayout_2.setStretch(0, 9)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        ConsultWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConsultWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsultWindow)

    def retranslateUi(self, ConsultWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsultWindow.setWindowTitle(_translate("ConsultWindow", "Консультирование"))
        self.butonUnselcetAll.setText(_translate("ConsultWindow", "Сбросить выбор"))
        self.buttonProcess.setText(_translate("ConsultWindow", "Произвести вывод"))
