# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(418, 337)
        MainWindow.setMaximumSize(QtCore.QSize(700, 420))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(770, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonLoadDatabase = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLoadDatabase.sizePolicy().hasHeightForWidth())
        self.buttonLoadDatabase.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonLoadDatabase.setFont(font)
        self.buttonLoadDatabase.setAutoDefault(False)
        self.buttonLoadDatabase.setDefault(False)
        self.buttonLoadDatabase.setFlat(False)
        self.buttonLoadDatabase.setObjectName("buttonLoadDatabase")
        self.verticalLayout.addWidget(self.buttonLoadDatabase)
        self.buttonInitEmptyDatabase = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInitEmptyDatabase.sizePolicy().hasHeightForWidth())
        self.buttonInitEmptyDatabase.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonInitEmptyDatabase.setFont(font)
        self.buttonInitEmptyDatabase.setObjectName("buttonInitEmptyDatabase")
        self.verticalLayout.addWidget(self.buttonInitEmptyDatabase)
        self.buttonConsultMode = QtWidgets.QPushButton(self.centralwidget)
        self.buttonConsultMode.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConsultMode.sizePolicy().hasHeightForWidth())
        self.buttonConsultMode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonConsultMode.setFont(font)
        self.buttonConsultMode.setObjectName("buttonConsultMode")
        self.verticalLayout.addWidget(self.buttonConsultMode)
        self.buttonBaseEditMode = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBaseEditMode.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBaseEditMode.sizePolicy().hasHeightForWidth())
        self.buttonBaseEditMode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonBaseEditMode.setFont(font)
        self.buttonBaseEditMode.setObjectName("buttonBaseEditMode")
        self.verticalLayout.addWidget(self.buttonBaseEditMode)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню"))
        self.buttonLoadDatabase.setText(_translate("MainWindow", "Загрузить базу знаний"))
        self.buttonInitEmptyDatabase.setText(_translate("MainWindow", "Создать пустую базу знаний"))
        self.buttonConsultMode.setText(_translate("MainWindow", "Консультация"))
        self.buttonBaseEditMode.setText(_translate("MainWindow", "Редактирование базы знаний"))
